language: java
sudo: false
cache:
  directories:
  - "$HOME/.m2"

#Configurando SonnarCloud
addons:
  sonarcloud:
    organization: "ylvaldes-github"
    token:
        secure: "5a065e8d4122f1597ff44ca2293f5e814144025f"

script: 
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=ylvaldes_FacturatoWaller
  
notifications:
  - webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
  - slack: developerteamgrupo:IykMDkddgWiZEjsshJAiJeYx