language: java
sudo: false
cache:
  directories:
  - "$HOME/.m2"


script: 
  - mvn clean verify 
  - mvn clean install  
 notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify